apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      istioNamespace: istio-system
  profile: demo
  components:
    ingressGateways:
      - enabled: true
        name: istio-ingressgateway
        k8s:
          service:
            ports:
              - name: http2
                port: 80
                targetPort: 80
                nodePort: 30080
              -
                name: status-port
                port: 15020
                targetPort: 15020
              -
                name: https
                port: 443
                nodePort: 30443
              -
                name: kiali
                port: 15029
                targetPort: 15029
              -
                name: prometheus
                port: 15030
                targetPort: 15030
              -
                name: grafana
                port: 15031
                targetPort: 15031
