version: '2'
silent: true
env:
  KUBECONFIG: kubeconfig.yml

tasks:
  default:
    cmds:
      - echo "Check the README.md"

  build:download_images:
    desc: Downloads the docker images for offline usage
    summary: |
      It will download all the requird docker images mentioned in docker_images/docker_images_list.txt
      So that you can run the demo without internet. And avoid downloading them multiple times.
    cmds:
      - ./bin/save_docker_images.sh

  build:
    cmds:
      - ./bin/download-k3s.sh

  infra:deploy:
    desc: Starts the Vagrant box and installs single node k8s
    deps: [build]
    preconditions:
      - test -f bin/k3s
      - test -f docker_images/k3s-airgap-images-amd64-v1.17.4.tar
    cmds:
      - vagrant up
      - sleep 5
      - kubectl get nodes

  infra:destroy:
    desc: Destroy the vagrant box.
    cmds:
      - vagrant destroy -f

  app:deploy:kubeless:
    desc: Deploy the kubeless on this vagrant box
    preconditions:
      - vagrant up
    cmds:
      - kubectl apply -f config/kubeless-v1.0.6.yaml
      - kubectl get pods -n kubeless

  app:destroy:kubeless:
    desc: Destory the kubeless on this vagrant box
    cmds:
      - kubectl delete -f config/kubeless-v1.0.6.yaml
      - kubectl delete function hello

  app:deploy:fission:
    desc: Deploy the kubeless on this vagrant box
    preconditions:
      - vagrant up
    cmds:
      - kubectl apply -f config/fission-core-1.8.0.yaml
      - kubectl get pods -n fission

  app:destroy:fission:
    desc: Destory the kubeless on this vagrant box
    cmds:
      - kubectl delete function hello-fission
      - kubectl delete -f config/fission-core-1.8.0.yaml