version: '2'
silent: true
env:
  KUBECONFIG: kubeconfig.yml

tasks:
  deploy:
    desc: Starts the Vagrant box and installs single node k8s
    deps: [build:binary]
    preconditions:
      - test -f bin/k3s
      - test -f docker_images/k3s-airgap-images-amd64-v1.17.4.tar
    cmds:
      - vagrant up
      - sleep 5
      - kubectl get nodes

  destroy:
    desc: Destroy the vagrant box.
    cmds:
      - vagrant destroy -f