#Despite adding the imagePullPolicy to IfNotPresent, the knative controller will try to download the image. As it used the image SHA
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-demo-python
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: dev.local/junaid18183/knative-demo-python:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TARGET
              value: "Python Sample v1"
